version: 2.0

workflow:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy-master:
        filters:
          branches:
            only: master
      
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    branches:
      only:
        - develop
    working_directory: ~/controlCamionesApi
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v ohl@64.227.61.249 "/home/ohl/controlCamionesApi/mantenedor/.circleci/deploy_app_qa.sh"

  deploy-master:
    docker:
      - image: circleci/python:3.7.6
    branches:
      only:
        - master
    working_directory: ~/controlCamionesApi
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v ohl@157.245.237.33 "/home/ohl/controlCamionesApi/mantenedor/.circleci/deploy_app_prod.sh"
